### ISSUE TITLE
Undefined variable: b:current_syntax

### ISSUE THREAD

**Issue by ianks** [keith/rspec.vim#23]
```
/home/ianks/.yadr/editors/vim/plugged/rspec.vim/syntax/rspec.vim, line 7
Vim(let):E121: Undefined variable: b:current_syntax
Error occurred while executing "open" action!
```

Since #22 was merged I have been getting this error when opening any `*_spec.rb` file. `b:current_syntax` is not guanteed to be defined, and it seems it fails at this point. I am not sure why this is different in my case, but it seems ruby syntax is not loaded before the rspec.vim is loaded.

**Comment by keith** [comment]
I've reverted that PR until we have a fix. https://github.com/keith/rspec.vim/pull/24

Thanks!
