### ISSUE TITLE
Filetype

### ISSUE THREAD

**Issue by petRUShka** [keith/rspec.vim#27]
Why is `filetype` equal to `rspec` and not to `ruby.rspec`?

**Comment by keith** [comment]
Yep, it should be `ruby.rspec`. There was a PR for this but it caused this issue https://github.com/keith/rspec.vim/issues/23 so I had to revert it. Feel free to submit a modified version that fixes this!

**Comment by keith** [comment]
Feel free to submit a PR for this if it's still an issue!
